package life.iGuaDa.community.model;

public class Report {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.id
     *
     * @mbg.generated Thu Jun 16 17:40:21 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.user_id
     *
     * @mbg.generated Thu Jun 16 17:40:21 CST 2022
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.question_id
     *
     * @mbg.generated Thu Jun 16 17:40:21 CST 2022
     */
    private Long questionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.id
     *
     * @return the value of report.id
     *
     * @mbg.generated Thu Jun 16 17:40:21 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.id
     *
     * @param id the value for report.id
     *
     * @mbg.generated Thu Jun 16 17:40:21 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.user_id
     *
     * @return the value of report.user_id
     *
     * @mbg.generated Thu Jun 16 17:40:21 CST 2022
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.user_id
     *
     * @param userId the value for report.user_id
     *
     * @mbg.generated Thu Jun 16 17:40:21 CST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.question_id
     *
     * @return the value of report.question_id
     *
     * @mbg.generated Thu Jun 16 17:40:21 CST 2022
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.question_id
     *
     * @param questionId the value for report.question_id
     *
     * @mbg.generated Thu Jun 16 17:40:21 CST 2022
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }
}